### ISSUE TITLE
CompoundSelectCommand does not generate LIMIT or OFFSET commands in query 

### ISSUE THREAD

**Issue by lopezca** [pharo-rdbms/glorp#53]
When producing SQL from a `CompoundQuery` object (created by calling `unionAll:` on 2 queries) , it uses a  `CompoundSelectCommand` object to wrap a SELECT DISTINCT query to the union.

The `CompoundQuery` object has the `limit:` and `offset:` messages, but they do not store any values and simply state:
> We currently ignore limit sets and use the one from our contained queries.

Moreover, the `CompoundSelectCommand` does account for these values and does not generate any SQL even if they are not nil (which is the check `SimpleQuery` uses).

There are 2 problems with the current implementation:
1) `CompoundQuery` should have its own limit and offset variables since the internal queries may have something different for their own reasons (for example `count:` queries set limit=1 by default).

2) CompoundSelectCommand should print LIMIT and OFFSET if the CompoundQuery object has values.

I propose the following changes:

1) Add instance variables (limit, offset) to `CompoundQuery` to store it's own values, independently of the first union query.

2) Have `CompoundSelectCommand` add the wrapper SELECT statement if we have limit or offset values.

**Comment by gcotelli** [comment]
Fixed by #54

**Comment by lopezca** [comment]
thanks @gcotelli !
