### ISSUE TITLE
SQLite3: Tests showing errors

### ISSUE THREAD

**Issue by sanjayminni** [pharo-rdbms/glorp#59]
using SQLite3 Glorp-integration-tests shows 1 failure and 483 errors

Environment and SQLite3 were setup as follows
P10 image + Pharo-SQLite3 + glorp + Pharo-SQLite3(SQLite3-Glorp, SQLite3-Glorp-Tests)

```
GlorpDatabaseLoginResource class>>defaultLogin
	DefaultLogin isNil ifTrue: [^DefaultLogin := self defaultSQLiteLocalLogin].

PharoDatabaseAccessor>>connectionClassForLogin: aLogin 
...
        aLogin database class == SQLite3Platform
             ifTrue: [ ^ Smalltalk at: #SQLite3Driver ].

```

**Comment by astares** [comment]
Fails for Pharo 10 and 11 due to the usage of a deprecated method:

![image](https://user-images.githubusercontent.com/5980033/228519144-28d9c8cd-66e5-4385-85d2-5fc3dc85134d.png)

**Comment by astares** [comment]
OK - fixed another deprecation. 

But tests still fail, now for UTF-8 encoding issues:

![image](https://user-images.githubusercontent.com/5980033/228527271-62b0597d-32f9-426f-8162-739e653562c2.png)

**Comment by astares** [comment]
OK - this seems to be related to https://github.com/pharo-vcs/iceberg/pull/1611
and https://github.com/pharo-vcs/iceberg/issues/1184

which has been seen as a show stopper already also on #iceberg channel in Discord:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/5980033/228604198-21886977-59ac-46d5-853a-a50c327b32da.png">

**Comment by gcotelli** [comment]
Already fixed
