### ISSUE TITLE
ActiveRecordDescriptorSystem>>#constructAllClasses uses missing RBCreateAccessorsForVariableRefactoring

### ISSUE THREAD

**Issue by astares** [pharo-rdbms/glorp#63]
Pharo11:
- the method ActiveRecordDescriptorSystem>>#constructAllClasses uses missing RBCreateAccessorsForVariableRefactoring
- maybe RBCreateAccessorsForVariableTransformation needs to be used in the future

![image](https://user-images.githubusercontent.com/5980033/228508788-8c3038af-38be-4d9a-9351-b740cb6cf183.png)

**Comment by astares** [comment]
Introduced with https://github.com/pharo-project/pharo/pull/14134/

**Comment by tblanchard** [comment]
Well that’s annoying. When will we get a stable platform? I can’t keep rewriting stuff every release.Sent from my iPhoneOn Mar 29, 2023, at 3:40 AM, Astares ***@***.***> wrote:﻿
Pharo11:

the method ActiveRecordDescriptorSystem>>#constructAllClasses uses missing RBCreateAccessorsForVariableRefactoring
maybe RBCreateAccessorsForVariableTransformation needs to be used in the future

**Comment by astares** [comment]
@tblanchard Please define stable platform. World keeps spinning...
