### ISSUE TITLE
Cleanup: Unnecessary #new overrides

### ISSUE THREAD

**Issue by astares** [pharo-rdbms/glorp#66]
Some classes in GLORP override the #new method like

```Smalltalk
new

	^ super new initialize
```

for instance 

- Cache class>>#new
- CacheManager class>>#new
- DatabaseAccessor class>>#new
- GlorpSession class>>#new
- Login class>>#new
- PersistentObject class>>#new
- DatabaseCommand class>>#new
- TimedProxyReaper class>>#new
- DatabaseTable class>>#new
- GlorpPreparedStatement class>>#new
- GlorpExpression class>>#new
- Descriptor class>>#new
- DescriptorSystem class>>#new
- GlorpAttributeModel class>>#new
- GlorpClassModel class>>#new
- Mapping class>>#new
- AbstractProxy class>>#new
- ElementBuilder class>>#new
- Query class>>#new
- GlorpDatabaseType class>>#new
- FieldValueWrapper class>>#new
- RowMap class>>#new

This is not necessary in Pharo as this is already out of the box behavior that a new instance is initialized.

We can get rid of these methods

**Comment by lopezca** [comment]
This is all fixed and merged.
